spring:
  application:
    name: shopping-store
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/store
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none


logging:
  level:
    ru.yandex.practicum.shopping.store: TRACE
    org.springframework: ERROR
    org.zalando.logbook: TRACE