CREATE TABLE IF NOT EXISTS products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id UUID UNIQUE                             NOT NULL,
    fragile    BOOLEAN,
    width      DOUBLE PRECISION,
    height     DOUBLE PRECISION,
    depth      DOUBLE PRECISION,
    weight     DOUBLE PRECISION,
    quantity   BIGINT                                  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);